baseURL      = "/"
title        = "eggception"
theme        = "hello-friend-ng"
copyright    = "Julian Smolka"
languageCode = "en-us"

disableKinds    = ["RSS"]
customCSS       = []
customJS        = []
googleAnalytics = "UA-153991522-1"

[params]
  description  = "Homepage by Julian Smolka"
  keywords     = "computer science, programming, emulation"
  homeSubtitle = ""
  defaultTheme = "dark"

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02"

  disableReadOtherPosts = true

  [params.logo]
  logoText     = "eggception"
  logoHomeLink = "/"

  [[params.social]]
  name = "github"
  url  = "https://github.com/jsmolka"

[menu]
  [[menu.main]]
  identifier = "about"
  name       = "About"
  url        = "/about"

  [[menu.main]]
  identifier = "eggvance"
  name       = "eggvance"
  url        = "/eggvance"
