# Metadata
description  = "Homepage and blog by Julian Smolka"
keywords     = "homepage, blog, computer, science, development, programming, emulation"
homeSubtitle = "Computer Science Entity"

# Content
contentTypeName = "posts"
defaultTheme    = "dark"

# Datetime formats
dateFormatSingle = "2006-01-02"
dateFormatList   = "2006-01-02"
dateformNumTime  = "2006-01-02"

[logo]
logoText     = "throw eggception"
logoHomeLink = "/"

[[social]]
name = "github"
url  = "https://github.com/jsmolka"
