title = "smolka"
baseurl = "https://smolka.dev"
paginate = 8
disableKinds = ["taxonomyTerm"]
disableHugoGeneratorInject = true

[params]
  description = "Posts and other stuff."
  dateFormat = "2006/01/02"
  birthDate = "1998-05-11"

[menu]
  [[menu.header]]
    name = "About"
    url = "/about/"

  [[menu.header]]
    name = "Projects"
    url = "/projects/"

  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/jsmolka"

  [[menu.footer]]
    name = "RSS"
    url = "/index.xml"

  [[menu.footer]]
    name = "Strava"
    url = "https://www.strava.com/athletes/juliansmolka"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false

    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = false
