title = "Smolka"
baseurl = "https://smolka.dev"
paginate = 4
disableKinds = ["RSS", "taxonomyTerm"]
disableHugoGeneratorInject = true

[params]
  language = "en-US"
  description = "One obsession at a time."
  keywords = ["smolka", "cycling", "eggvance"]
  theme = "light"
  dateFormat = "2006/01/02"
  birthDate = "1998-05-11"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"

  [[menu.main]]
    name = "Drizzle"
    url = "/drizzle"

  [[menu.main]]
    name = "Eggvance"
    url = "/eggvance"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false

    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = false
