baseURL         = "/"
title           = "eggception"
copyright       = "Julian Smolka"
languageCode    = "en-us"
staticDir       = ["static", "icon/aseprite/web"]

[params]
  description = "Homepage and blog by Julian Smolka"
  keywords    = "programming, emulation, eggvance"
  themeColor  = "#ffffff"
