title = "smolka"
baseurl = "https://smolka.dev"
paginate = 5
disableKinds = ["RSS", "taxonomyTerm"]
disableHugoGeneratorInject = true

[params]
  language = "en-US"
  description = "Mediocre posts about emulation and micro optimizations."
  keywords = ["smolka", "blog", "eggvance"]
  defaultTheme = "light"
  dateFormat = "2006/01/02"
  birthDate = "1998-05-11"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"

  [[menu.main]]
    name = "eggvance"
    url = "/eggvance"

  [[menu.main]]
    name = "Posts"
    url = "/posts"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false

    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = false
