title = "smolka"
baseurl = "https://smolka.dev"
summaryLength = 25
disableKinds = ["taxonomy"]
disableHugoGeneratorInject = true

[params]
  description = "Living life one obsession at a time."
  birthDate = "1998-05-11"

[menu]
  [[menu.header]]
    name = "About"
    url = "/about/"

  [[menu.header]]
    name = "Projects"
    url = "/projects/"

  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/jsmolka"

  [[menu.footer]]
    name = "RSS"
    url = "/index.xml"

  [[menu.footer]]
    name = "Strava"
    url = "https://www.strava.com/athletes/juliansmolka"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions.typographer]
      apostrophe = "'"
      leftDoubleQuote = '"'
      leftSingleQuote = "'"
      rightDoubleQuote = '"'
      rightSingleQuote = "'"

    [markup.goldmark.parser.attribute]
      block = true

    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = false

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"

  [[module.mounts]]
    source = "content"
    target = "assets"

[build]
noJSConfigInAssets = true
