baseurl = "https://smolka.dev"
title = "smolka"
languageCode = "en-US"
paginate = 5
disableKinds = ["RSS", "taxonomyTerm"]
disableHugoGeneratorInject = true

[params]
  title = "Smolka"
  keywords = "smolka, blog, programming, emulation, eggvance, cycling"
  newerPosts = "Go forward in time"
  olderPosts = "Go back in time"
  minuteReadingTime = "min read"
  dateFormatSingle = "2006-01-02"
  dateFormatList = "2006-01-02"
  contentTypeName = "post"
  defaultTheme = "light"
  birthDate = "1998-05-11"

  [params.logo]
    logoText = "smolka"
    logoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"

  [[menu.main]]
    identifier = "eggvance"
    name = "eggvance"
    url = "/eggvance"

  [[menu.main]]
    identifier = "posts"
    name = "Post"
    url = "/post"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false

    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = false
