baseURL      = "/"
title        = "eggcpt"
copyright    = "Julian Smolka"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[author]
  name = "Julian Smolka"

[params]
  description     = "The homepage of Julian Smolka"
  github          = "jsmolka"
  birthDate       = "1998-05-11"
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

[menu]
  [[menu.main]]
    name = "About"
    url  = "/about"

  [[menu.main]]
    name = "eggvance"
    url  = "/eggvance"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = false

[module]
  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "icon/web"
    target = "static"

  [[module.mounts]]
    source = "icon/bin/icon-optimized.svg"
    target = "static/icon.svg"
