baseURL         = "/"
title           = "eggception"
copyright       = "Julian Smolka"
languageCode    = "en-us"
staticDir       = ["static", "icon/aseprite/web"]

[author]
  name = "Julian Smolka"

[params]
  description = "The homepage of Julian Smolka"

[menu]
  [[menu.main]]
  identifier = "about"
  name       = "About"
  url        = "/about"

  [[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/blog"

  [[menu.main]]
  identifier = "eggvance"
  name       = "eggvance"
  url        = "/eggvance"
