baseURL   = "/"
title     = "eggception"
copyright = "Julian Smolka"
staticDir = ["static", "icon/aseprite/web"]

[author]
  name = "Julian Smolka"

[params]
  description = "The homepage of Julian Smolka"
  github      = "jsmolka"

[menu]
  [[menu.main]]
  identifier = "about"
  name       = "About"
  url        = "/about"

  [[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "/blog"

  [[menu.main]]
  identifier = "eggvance"
  name       = "eggvance"
  url        = "/eggvance"
