title = "Smolka"
baseurl = "https://smolka.dev"
paginate = 10
disableKinds = ["taxonomyTerm"]
disableHugoGeneratorInject = true

[params]
  language = "en-US"
  description = "Just another dark corner of the internet."
  tags = ["smolka", "programming", "eggvance", "cycling"]
  theme = "light"
  dateFormat = "2006/01/02"
  birthDate = "1998-05-11"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"

  [[menu.main]]
    name = "Posts"
    url = "/posts"

  [[menu.main]]
    name = "Projects"
    url = "/projects"

  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/jsmolka"

  [[menu.footer]]
    name = "RSS"
    url = "/index.xml"

  [[menu.footer]]
    name = "Strava"
    url = "https://www.strava.com/athletes/juliansmolka"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = true

    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    codeFences = false
