baseURL         = "/"
title           = "eggception"
theme           = "hello-friend-ng"
copyright       = "Julian Smolka"
languageCode    = "en-us"
disableRSS      = true
paginate        = 5
googleAnalytics = "UA-153991522-1"

[params]
  # Metadata
  description  = "Homepage by Julian Smolka"
  keywords     = "computer science, programming, emulation"
  homeSubtitle = "Computer Science Entity"

  # Content
  contentTypeName = "posts"
  defaultTheme    = "dark"

  # Datetime formats
  dateFormatSingle = "2006-01-02"
  dateFormatList   = "2006-01-02"
  dateformNumTime  = "2006-01-02"

  [logo]
  logoText     = "eggception"
  logoHomeLink = "/"

  [[social]]
  name = "github"
  url  = "https://github.com/jsmolka"

[menu]

  [[main]]
  identifier = "about"
  name       = "About"
  url        = "/about"

[[main]]
  identifier = "eggvance"
  name       = "eggvance"
  url        = "/eggvance"
